language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install argparse, fnmatch, getpass, os, glob, random, re, stat, subprocess, sys, time, io, BytesIO, pprint, requests, yaml, Image